[build]
command = "npm run build"
output_directory = "out"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

[build.install]
command = "npm ci --include=dev"

[env.production]
name = "cardity-web-production"

[env.staging]
name = "cardity-web-staging"
